@Ires.Api_HostAddress = http://localhost:5046

### Create Person

POST {{Ires.Api_HostAddress}}/api/v1.0/people
Content-Type: application/json
Accept: application/json

{
  "given_name": "John",
  "family_name": "Doe",
  "gender": "Male",
  "date_of_birth": "1998-09-26",
  "notes": "Blah blah blah."
}

### Get People

GET {{Ires.Api_HostAddress}}/api/v1.0/people
Accept: application/json



### Create Address
POST {{Ires.Api_HostAddress}}/api/v1.0/address
Content-Type: application/json
Accept: application/json

{
  "street": "123 Main St",
  "city": "Springfield",
  "state": "IL",
  "postal_code": "62704",
  "country": "USA",
  "address_type": "Home"
}


### Add Address to Person
PUT {{Ires.Api_HostAddress}}/api/v1.0/people/ed86c4fe-a196-43ab-8c45-4f0fc15d0b0c
Content-Type: application/json
Accept: application/json

{
  "address_id": "1fe83300-c2b5-48f0-81d0-967379c15019"
}