@Ires.Api_HostAddress = http://localhost:5046

### Create Person

POST {{Ires.Api_HostAddress}}/api/v1.0/people
Content-Type: application/json
Accept: application/json

{
  "given_name": "John",
  "family_name": "Doe",
  "gender": "Male",
  "date_of_birth": "1998-09-26",
  "notes": "Blah blah blah."
}

### Get People

GET {{Ires.Api_HostAddress}}/api/v1.0/people
Accept: application/json

