@Ires.Helper_HostAddress = http://localhost:5158

POST {{Ires.Helper_HostAddress}}/register
Content-Type: application/json
Accept: application/json

{
    "username": "your_username_here",
    "password": "your_password_here"
}
